apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins-agent
  name: jenkins-pod-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"] # Add create and delete verbs for Pod creation and deletion

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-pod-creator-binding
  namespace: jenkins-agent
subjects:
- kind: ServiceAccount
  name: jenkinsservice
  namespace: jenkins-agent
roleRef:
  kind: Role
  name: jenkins-pod-creator
  apiGroup: rbac.authorization.k8s.io
